#!/bin/sh

alias ggrep='grep -E --color=always --line-buffered'
OLD_IFS=$IFS # Save IFS
IFS='|'

# Because the IFS is '|', the variable $* will expand to
# all the parameters separated by '|' (e.g: "foo|bar|baz"),
# resulting in an OR expression.
# The first line searches for all the patterns in the standard input.
# The following lines colorizes every argument with a different color.
# If the argument doesn't exists we just 'cat' so that the output of
# previous commands goes through.
# If the argument exists we grep it but we also add '|$' to our pattern
# to match every line. That way we don't lose the output of previous
# commands.
# This is why we need the first 'grep $*' to select only the lines we want.
cmd="grep -E --color=never \"$*\""

IFS=$OLD_IFS # Restore IFS

for i in `seq $#`; do
  color="1;3$i"
  cmd="$cmd | GREP_COLOR=\"$color\" ggrep \"$1|$\""
  shift
done
eval $cmd

unalias ggrep
